### ISSUE TITLE
List Index Out of Range When Closing a Ticket

### ISSUE THREAD

**Issue by href** [OneGov/onegov.town#107]
```python
TRACEBACK:
Traceback (most recent call last):
  File "/opt/onegov-town/lib/python3.4/site-packages/morepath/app.py", line 142, in __call__
    response = self.publish(request)
  File "/opt/onegov-town/lib/python3.4/site-packages/onegov/core/framework.py", line 761, in http_conflict_tween
    return handler(request)
  File "/opt/onegov-town/lib/python3.4/site-packages/onegov/search/integration.py", line 205, in process_indexer_tween
    result = handler(request)
  File "/opt/onegov-town/lib/python3.4/site-packages/more/transaction/main.py", line 88, in transaction_tween
    reraise(*exc_info)
  File "/opt/onegov-town/lib/python3.4/site-packages/more/transaction/compat.py", line 13, in reraise
    raise value
  File "/opt/onegov-town/lib/python3.4/site-packages/more/transaction/main.py", line 69, in transaction_tween
    response = handler(request)
  File "/opt/onegov-town/lib/python3.4/site-packages/morepath/core.py", line 128, in excview_tween
    response = handler(request)
  File "/opt/onegov-town/lib/python3.4/site-packages/onegov/core/framework.py", line 718, in fix_webassets_url
    response = handler(request)
  File "/opt/onegov-town/lib/python3.4/site-packages/more/webassets/tweens.py", line 123, in __call__
    return self.handler(request)
  File "/opt/onegov-town/lib/python3.4/site-packages/more/webassets/tweens.py", line 75, in __call__
    response = self.handler(request)
  File "/opt/onegov-town/lib/python3.4/site-packages/morepath/publish.py", line 71, in publish
    return resolve_response(request, model)
  File "/opt/onegov-town/lib/python3.4/site-packages/morepath/publish.py", line 54, in resolve_response
    return view.response(request, obj)
  File "/opt/onegov-town/lib/python3.4/site-packages/morepath/view.py", line 28, in response
    content = self(request, obj)
  File "/opt/onegov-town/lib/python3.4/site-packages/morepath/view.py", line 19, in __call__
    return self.func(model, request)
  File "/opt/onegov-town/lib/python3.4/site-packages/onegov/town/views/ticket.py", line 61, in close_ticket
    email = self.snapshot.get('email') or self.handler.email
  File "/opt/onegov-town/lib/python3.4/site-packages/onegov/town/models/ticket.py", line 128, in email
    return self.reservations[0].email
IndexError: list index out of range
````

When calling /ticket/RSV/xxx/close

**Comment by href** [comment]
For some reason the reservations @ Dürrenäsch do not contain any snapshot data. They even have reservations with tickets which were never approved without any reservation data with them.

This is *very* weird and I can't reproduce it locally or on the actual Dürrenäsch instance, even though I've tried a number of weird ways you could possibly trip up the system.

We have to keep an eye on this one...

**Comment by href** [comment]
For now I fixed the data on the Dürrenäsch instance..

**Comment by href** [comment]
The problem was that the final reservation step did not confirm the reservations. Therefore they were later cleaned out, even though they were approved.

This is something libres should have been vocal about:
https://github.com/seantis/libres/issues/11
