### ISSUE TITLE
An Exception Occurs if a Form is Added With an Existing Name

### ISSUE THREAD

**Issue by href** [OneGov/onegov.town#136]
```python
TRACEBACK:
Traceback (most recent call last):
 File "/opt/onegov-town/lib/python3.4/site-packages/morepath/app.py", line 142, in __call__
   response = self.publish(request)
 File "/opt/onegov-town/lib/python3.4/site-packages/onegov/core/framework.py", line 765, in http_conflict_tween
   return handler(request)
 File "/opt/onegov-town/lib/python3.4/site-packages/onegov/search/integration.py", line 205, in process_indexer_tween
   result = handler(request)
 File "/opt/onegov-town/lib/python3.4/site-packages/more/transaction/main.py", line 88, in transaction_tween
   reraise(*exc_info)
 File "/opt/onegov-town/lib/python3.4/site-packages/more/transaction/compat.py", line 13, in reraise
   raise value
 File "/opt/onegov-town/lib/python3.4/site-packages/more/transaction/main.py", line 69, in transaction_tween
   response = handler(request)
 File "/opt/onegov-town/lib/python3.4/site-packages/morepath/core.py", line 128, in excview_tween
   response = handler(request)
 File "/opt/onegov-town/lib/python3.4/site-packages/onegov/core/framework.py", line 722, in fix_webassets_url
   response = handler(request)
 File "/opt/onegov-town/lib/python3.4/site-packages/more/webassets/tweens.py", line 123, in __call__
   return self.handler(request)
 File "/opt/onegov-town/lib/python3.4/site-packages/more/webassets/tweens.py", line 75, in __call__
   response = self.handler(request)
 File "/opt/onegov-town/lib/python3.4/site-packages/morepath/publish.py", line 71, in publish
   return resolve_response(request, model)
 File "/opt/onegov-town/lib/python3.4/site-packages/morepath/publish.py", line 54, in resolve_response
   return view.response(request, obj)
 File "/opt/onegov-town/lib/python3.4/site-packages/morepath/view.py", line 28, in response
   content = self(request, obj)
 File "/opt/onegov-town/lib/python3.4/site-packages/morepath/view.py", line 19, in __call__
   return self.func(model, request)
 File "/opt/onegov-town/lib/python3.4/site-packages/onegov/core/directive.py", line 83, in handle_form
   return obj(self, request, form)
 File "/opt/onegov-town/lib/python3.4/site-packages/onegov/town/views/form_definition.py", line 44, in handle_new_definition
   content=model.content
 File "/opt/onegov-town/lib/python3.4/site-packages/onegov/form/collection.py", line 91, in add
   self.session.flush()
 File "/opt/onegov-town/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 2015, in flush
   self._flush(objects)
 File "/opt/onegov-town/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 2133, in _flush
   transaction.rollback(_capture_exception=True)
 File "/opt/onegov-town/lib/python3.4/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
   compat.reraise(exc_type, exc_value, exc_tb)
 File "/opt/onegov-town/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 182, in reraise
   raise value
 File "/opt/onegov-town/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 2097, in _flush
   flush_context.execute()
 File "/opt/onegov-town/lib/python3.4/site-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
   rec.execute(self)
 File "/opt/onegov-town/lib/python3.4/site-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
   uow
 File "/opt/onegov-town/lib/python3.4/site-packages/sqlalchemy/orm/persistence.py", line 174, in save_obj
   mapper, table, insert)
 File "/opt/onegov-town/lib/python3.4/site-packages/sqlalchemy/orm/persistence.py", line 752, in _emit_insert_statements
   execute(statement, multiparams)
 File "/opt/onegov-town/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 914, in execute
   return meth(self, multiparams, params)
 File "/opt/onegov-town/lib/python3.4/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
   return connection._execute_clauseelement(self, multiparams, params)
 File "/opt/onegov-town/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
   compiled_sql, distilled_params
 File "/opt/onegov-town/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
   context)
 File "/opt/onegov-town/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
   exc_info
 File "/opt/onegov-town/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 188, in raise_from_cause
   reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
 File "/opt/onegov-town/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 181, in reraise
   raise value.with_traceback(tb)
 File "/opt/onegov-town/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
   context)
 File "/opt/onegov-town/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
   cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) duplicate key value violates unique constraint "forms_pkey"
DETAIL:  Key (name)=(auszugsanzeige) already exists.
```

**Comment by href** [comment]
For now we'll just show a better error message. In the future we might have to add some auto-numbering to the id because people might want to add a form with the same name (to replace a built-in one). Though this is possibly an issue we should look at differently (give a way to *replace* a builtin form).
