### ISSUE TITLE
Catch Yubikey Exceptions

### ISSUE THREAD

**Issue by href** [OneGov/onegov.town#206]
We have two kinds of yubikey exceptions we don't catch yet, though we should:

```python
TRACEBACK:
Traceback (most recent call last):
 File "/opt/onegov-town/lib/python3.4/site-packages/morepath/app.py", line 109, in __call__
   response = self.publish(request)
 File "/opt/onegov-town/lib/python3.4/site-packages/morepath/core.py", line 226, in poisoned_host_header_protection_tween
   return handler(request)
 File "/opt/onegov-town/lib/python3.4/site-packages/onegov/core/framework.py", line 819, in current_language_tween
   return handler(request)
 File "/opt/onegov-town/lib/python3.4/site-packages/onegov/core/framework.py", line 790, in http_conflict_tween
   return handler(request)
 File "/opt/onegov-town/lib/python3.4/site-packages/onegov/search/integration.py", line 212, in process_indexer_tween
   result = handler(request)
 File "/opt/onegov-town/lib/python3.4/site-packages/more/transaction/main.py", line 88, in transaction_tween
   reraise(*exc_info)
 File "/opt/onegov-town/lib/python3.4/site-packages/more/transaction/compat.py", line 13, in reraise
   raise value
 File "/opt/onegov-town/lib/python3.4/site-packages/more/transaction/main.py", line 69, in transaction_tween
   response = handler(request)
 File "/opt/onegov-town/lib/python3.4/site-packages/morepath/core.py", line 185, in excview_tween
   response = handler(request)
 File "/opt/onegov-town/lib/python3.4/site-packages/onegov/core/framework.py", line 737, in fix_webassets_url
   response = handler(request)
 File "/opt/onegov-town/lib/python3.4/site-packages/more/webassets/tweens.py", line 132, in __call__
   return self.handler(request)
 File "/opt/onegov-town/lib/python3.4/site-packages/more/webassets/tweens.py", line 84, in __call__
   response = self.handler(request)
 File "/opt/onegov-town/lib/python3.4/site-packages/onegov/core/framework.py", line 850, in spawn_cronjob_thread_tween
   return handler(request)
 File "/opt/onegov-town/lib/python3.4/site-packages/onegov/gis/integration.py", line 66, in inject_mapbox_api_token_tween
   response = handler(request)
 File "/opt/onegov-town/lib/python3.4/site-packages/morepath/publish.py", line 41, in publish
   return resolve_response(obj, request)
 File "/opt/onegov-town/lib/python3.4/site-packages/morepath/publish.py", line 140, in resolve_response
   return generic.view(obj, request, lookup=request.lookup)
 File "/opt/onegov-town/lib/python3.4/site-packages/reg/dispatch.py", line 55, in __call__
   return lookup.call(self.wrapped_func, *args, **kw)
 File "/opt/onegov-town/lib/python3.4/site-packages/reg/registry.py", line 408, in call
   return lookup_mapply(component, self, *args, **kw)
 File "/opt/onegov-town/lib/python3.4/site-packages/reg/mapply.py", line 33, in lookup_mapply
   return func(*args, **kw)
 File "/opt/onegov-town/lib/python3.4/site-packages/morepath/view.py", line 70, in __call__
   content = self.func(obj, request)
 File "/opt/onegov-town/lib/python3.4/site-packages/onegov/core/directive.py", line 95, in handle_form
   return obj(self, request, form)
 File "/opt/onegov-town/lib/python3.4/site-packages/onegov/town/views/auth.py", line 18, in handle_login
   response = self.login_to(request=request, **form.login_data)
 File "/opt/onegov-town/lib/python3.4/site-packages/onegov/user/auth.py", line 150, in login_to
   second_factor)
 File "/opt/onegov-town/lib/python3.4/site-packages/onegov/user/auth.py", line 127, in login
   if not self.is_valid_second_factor(user, second_factor):
 File "/opt/onegov-town/lib/python3.4/site-packages/onegov/user/auth.py", line 100, in is_valid_second_factor
   yubikey=second_factor_value
 File "/opt/onegov-town/lib/python3.4/site-packages/onegov/user/auth.py", line 39, in is_valid_yubikey
   return Yubico(client_id, secret_key).verify(yubikey)
 File "/opt/onegov-town/lib/python3.4/site-packages/yubico_client/yubico.py", line 161, in verify
   raise Exception('NO_VALID_ANSWERS')
Exception: NO_VALID_ANSWERS
```
and
```python
TRACEBACK:
Traceback (most recent call last):
 File "/opt/onegov-town/lib/python3.4/site-packages/morepath/app.py", line 109, in __call__
   response = self.publish(request)
 File "/opt/onegov-town/lib/python3.4/site-packages/morepath/core.py", line 226, in poisoned_host_header_protection_tween
   return handler(request)
 File "/opt/onegov-town/lib/python3.4/site-packages/onegov/core/framework.py", line 819, in current_language_tween
   return handler(request)
 File "/opt/onegov-town/lib/python3.4/site-packages/onegov/core/framework.py", line 790, in http_conflict_tween
   return handler(request)
 File "/opt/onegov-town/lib/python3.4/site-packages/onegov/search/integration.py", line 212, in process_indexer_tween
   result = handler(request)
 File "/opt/onegov-town/lib/python3.4/site-packages/more/transaction/main.py", line 88, in transaction_tween
   reraise(*exc_info)
 File "/opt/onegov-town/lib/python3.4/site-packages/more/transaction/compat.py", line 13, in reraise
   raise value
 File "/opt/onegov-town/lib/python3.4/site-packages/more/transaction/main.py", line 69, in transaction_tween
   response = handler(request)
 File "/opt/onegov-town/lib/python3.4/site-packages/morepath/core.py", line 185, in excview_tween
   response = handler(request)
 File "/opt/onegov-town/lib/python3.4/site-packages/onegov/core/framework.py", line 737, in fix_webassets_url
   response = handler(request)
 File "/opt/onegov-town/lib/python3.4/site-packages/more/webassets/tweens.py", line 132, in __call__
   return self.handler(request)
 File "/opt/onegov-town/lib/python3.4/site-packages/more/webassets/tweens.py", line 84, in __call__
   response = self.handler(request)
 File "/opt/onegov-town/lib/python3.4/site-packages/onegov/core/framework.py", line 850, in spawn_cronjob_thread_tween
   return handler(request)
 File "/opt/onegov-town/lib/python3.4/site-packages/onegov/gis/integration.py", line 66, in inject_mapbox_api_token_tween
   response = handler(request)
 File "/opt/onegov-town/lib/python3.4/site-packages/morepath/publish.py", line 41, in publish
   return resolve_response(obj, request)
 File "/opt/onegov-town/lib/python3.4/site-packages/morepath/publish.py", line 140, in resolve_response
   return generic.view(obj, request, lookup=request.lookup)
 File "/opt/onegov-town/lib/python3.4/site-packages/reg/dispatch.py", line 55, in __call__
   return lookup.call(self.wrapped_func, *args, **kw)
 File "/opt/onegov-town/lib/python3.4/site-packages/reg/registry.py", line 408, in call
   return lookup_mapply(component, self, *args, **kw)
 File "/opt/onegov-town/lib/python3.4/site-packages/reg/mapply.py", line 33, in lookup_mapply
   return func(*args, **kw)
 File "/opt/onegov-town/lib/python3.4/site-packages/morepath/view.py", line 70, in __call__
   content = self.func(obj, request)
 File "/opt/onegov-town/lib/python3.4/site-packages/onegov/core/directive.py", line 95, in handle_form
   return obj(self, request, form)
 File "/opt/onegov-town/lib/python3.4/site-packages/onegov/town/views/auth.py", line 18, in handle_login
   response = self.login_to(request=request, **form.login_data)
 File "/opt/onegov-town/lib/python3.4/site-packages/onegov/user/auth.py", line 150, in login_to
   second_factor)
 File "/opt/onegov-town/lib/python3.4/site-packages/onegov/user/auth.py", line 127, in login
   if not self.is_valid_second_factor(user, second_factor):
 File "/opt/onegov-town/lib/python3.4/site-packages/onegov/user/auth.py", line 100, in is_valid_second_factor
   yubikey=second_factor_value
 File "/opt/onegov-town/lib/python3.4/site-packages/onegov/user/auth.py", line 39, in is_valid_yubikey
   return Yubico(client_id, secret_key).verify(yubikey)
 File "/opt/onegov-town/lib/python3.4/site-packages/yubico_client/yubico.py", line 150, in verify
   return_response)
 File "/opt/onegov-town/lib/python3.4/site-packages/yubico_client/yubico.py", line 257, in verify_response
   signature)
yubico_client.yubico_exceptions.SignatureVerificationError: 'Server response message signature verification failed(expected ..., got ...)'
```

**Comment by href** [comment]
Signature verifcation errors are now correctly caught. No valid answer errors show that no connection to the Yubico server could be made, in which case the exception is justified (and useful because we are notified).
