### ISSUE TITLE
If an event contains a unicode character in the title, no e-mail is sent

### ISSUE THREAD

**Issue by href** [OneGov/onegov.town#55]
I tried this title: "Party at my House 😀"

Note that for some reason, the emoji also doesn't render on the homepage view.

**Comment by msom** [comment]
The rendering seems to be an issue with Chrome (https://code.google.com/p/chromium/issues/detail?id=468765)

**Comment by msom** [comment]
ERROR: Failed to send e-mail
Traceback (most recent call last):
  File "/Users/marc/Projects/onegov.cloud/src/onegov.core/onegov/core/datamanager.py", line 30, in commit
    self.postman.send(self.envelope)
  File "/Users/marc/Projects/onegov.cloud/eggs/mailthon-0.1.1-py3.4.egg/mailthon/postman.py", line 91, in send
    return self.deliver(conn, envelope)
  File "/Users/marc/Projects/onegov.cloud/eggs/mailthon-0.1.1-py3.4.egg/mailthon/postman.py", line 81, in deliver
    envelope.string(),
  File "/Users/marc/Projects/onegov.cloud/eggs/mailthon-0.1.1-py3.4.egg/mailthon/envelope.py", line 81, in string
    return self.mime().as_string()
  File "/Users/marc/Projects/onegov.cloud/eggs/mailthon-0.1.1-py3.4.egg/mailthon/envelope.py", line 71, in mime
    mime.attach(item.mime())
  File "/Users/marc/Projects/onegov.cloud/eggs/mailthon-0.1.1-py3.4.egg/mailthon/enclosure.py", line 49, in mime
    mime = self.mime_object()
  File "/Users/marc/Projects/onegov.cloud/eggs/mailthon-0.1.1-py3.4.egg/mailthon/enclosure.py", line 74, in mime_object
    self.encoding)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/email/mime/text.py", line 41, in __init__
    self.set_payload(_text, _charset)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/email/message.py", line 316, in set_payload
    payload = payload.encode(charset.output_charset)
UnicodeEncodeError: 'latin-1' codec can't encode character '\U0001f600' in position 4331: ordinal not in range(256)

**Comment by msom** [comment]
Not all (utf8) characters might be present in the encoding (latin-1) used for the mails (https://github.com/OneGov/onegov.core/blob/master/onegov/core/framework.py#L504).

@href Can we assume that this might happen at other places as well (since we use utf8 everywhere and latin-1 only for sending mail per default) and handle it at the framework? We could ensure that the content and subject can be encoded with the given encoding (e.g. using ``ignore``on encode).

**Comment by href** [comment]
Sure, we should fix it there.

**Comment by href** [comment]
Fixed in https://github.com/OneGov/onegov.core/commit/e0927786d951fcad77c18c777ee92212f9e3428f
